### ISSUE TITLE
Issue in reproducing the results using sample code 

### ISSUE THREAD

**Issue by girishgr8** [kmanev/ZynqUSp-AXI-Speedtest#1]
@kmanev,

I am Girish Thatte, a Master's student in Computer Science & Engineering from the Indian Institute of Technology, Hyderabad (IIT Hyderabad) in India. 

I am trying to reproduce the results obtained in the paper ["Unexpected Diversity: Quantitative Memory Analysis for Zynq UltraScale+ Systems"](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8977835) published by you all, as my Master's thesis also involves memory tests and performance analysis.

I am using Vivado 2022.2 version for design & Vitis IDE for software development and Xilinx ZCU102 Evaluation Board.
However, I get the wrong results when I try to use the sample "[helloworld.c](https://github.com/kmanev/ZynqUSp-AXI-Speedtest/blob/master/IP/Driver%20Example/helloworld.c)" provided in the GitHub repository to perform read-only tests. I see an opposite trend as when I increase the burst-byte size, the average read latency increases and read speed (in MB/s) decreases. Moreover, I get the read speed for the 16B burst size as 113262.985 MB/s, which cannot be a practical value.
Following is the output that I get when I run 16B bursts for HP0 read-only tests:

Test Finished in 5.000 sec.
Write Speed: 0.000 MB/s
Read Speed 113262.985 MB/s
Avg. Read Latency: 68.480 clock cycles
Max Read AXI inactivity: 62 clock cycles

Also, I tried to check using memory monitor in Vitis IDE, if the data is actually being written at the designated memory location for HP3 by running HP3 in a write-only configuration. But the memory view shows no changes in data at the designated location.

![image](https://github.com/kmanev/ZynqUSp-AXI-Speedtest/assets/43734717/06393993-d209-416a-9d0a-d104a2a04e2c)
[Image on the left is the memory view after the test and the one on the right is before the test]

@kmanev, It would be really helpful if you could provide the source code of the custom MemoryTestBlock IP used in the paper, which will help me debug the issue I am facing.

**Comment by kmanev** [comment]
Hi Girish

**Comment by kmanev** [comment]
Hi Girish,
This sounds broken - both the "opposite" performance trend and the un-touched memory at those addresses.
Do you mind uploading your exact version of the .C file you use as well as the Vivado project? If you don't want to upload them publically, maybe you could share with me at KNMANEV [AT] gmail.com ?

I don't have the code for this block. But if it is anyhow broken in newer Vivado versions, it will probably be much easier for you to use the "AXI Traffic Generator" block in Vivado...

Cheers

**Comment by girishgr8** [comment]
Hi @kmanev,

Thank you so much for your response. I am attaching here the .c file I am using to regenerate the results.
Do you have any reference for using the AXI Traffic generator block in C to perform memory tests?

[helloworld.zip](https://github.com/kmanev/ZynqUSp-AXI-Speedtest/files/12374963/helloworld.zip)

I'm sorry for the delay in my response.

**Comment by kmanev** [comment]
Hi @girishgr8 

You will need to send in the whole brief testcase description + Vivado project + C source code + observed results, in order to check all steps match. Otherwise it cannot be verified.
The currently shared C code doesn't correspond to either of your two described testcases here: "Moreover, I get the read speed for the 16B burst size as 113262.985 MB/s, which cannot be a practical value. Following is the output that I get when I run 16B bursts for HP0 read-only tests:".

Did you follow all these steps: https://github.com/kmanev/ZynqUSp-AXI-Speedtest/blob/master/README.md
Including step 16?

You can find C code on how to run the Xilinx Traffic Generator here: https://github.com/Xilinx/embeddedsw/tree/master/XilinxProcessorIPLib/drivers/trafgen/examples

Cheers

**Comment by kmanev** [comment]
Assuming you've fixed your setup. Closing.

**Comment by kmanev** [comment]
Assuming you've fixed your setup. Closing
